== Clase Inaugural

Estudiantes, les envio link de zoom de la clase inaugural de Ia comisión de recursantes de "Algebra y Geometria Analitica 2024", para mañana jueves 08 de agosto de 2024 a las 18 h.

jueves 08 de agosto de 2024 a las 18 h.

Entrar Zoom Reunión

https://utn.zoom.us/j/6366199961?omn=99719807125

ID de reunión: 636 619 9961

Informo que:

* el curso es exclusivo para alumnos recursantes, no para alumnos que cursan por primera vez la materia, por Io tanto no es para ingresantes 2024.
* Tampoco se tomarán los casos que se hayan inscripto al cursado anual este año, y que también lo han hecho para el cursado de esta comisión.
* La modalidad del cursado se explicará mañana, en la clase inaugural. Se informará, entre otras cosas, que dado el gran número de alumnos, se organizaron 3 comisiones de cursado, para lo cual ustedes deberán optar por el horario, se armarán grupos de número homogéneos. Los dias y horarios son:
** Comisión A: jueves de 7:45 a 10:00 h;
** Comisión B: Jueves de 17:20 a 19:40 h; y
** Comisión C: miércoles de 19:40 a 22 h

Saludos,

